version: '3'

services:
  brp:
    build: .
    container_name: brp
    image: yoksar/brp
    ports:
      - 8600:8080
    environment:
      DB_URL: jdbc:mysql://192.168.178.24:3600/default
      DB_USER: mysql
      DB_PASS: mysql